version: "3.7"
services:
  db:
    build:
      context: ./db
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  hub:
    build:
      context: ./hub
    ports:
      - "5151:5151"
    depends_on:
      - db
      - mqtt_broker
  webapp:
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    depends_on:
      - hub
