version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883"
      - "9001"
  hub:
    build:
      context: ./hub
    ports:
      - "5151:5151"
    depends_on:
      - redis
      - mqtt_broker
