version: "3.7"
services:
  db:
    build:
      context: ./db
  mqtt_broker:
    image: eclipse-mosquitto
  hub:
    build:
      context: ./hub
    ports:
      - "5151:5151"
    depends_on:
      - db
      - mqtt_broker
