version: "3.7"
services:
  db:
    build:
      context: ./db
    environment:
      - POSTGRES_PASSWORD=TODO
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  hub:
    build:
      context: ./hub
    ports:
      - "5151:5151"
    environment:
      - MQTT_BROKER=tcp://mqtt_broker:1883
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TODO
      - DISABLE_AUTH=true
    depends_on:
      - db
      - mqtt_broker
