version: "3.7"
services:
  db:
    build:
      context: ./db
    environment:
      - POSTGRES_PASSWORD=TODO
  mqtt_broker:
    build:
      context: ./mqtt-broker
    ports:
      - "1883:1883"
  hub:
    build:
      context: ./hub
    ports:
      - "5151:5151"
    environment:
      - MQTT_BROKER=tcp://mqtt_broker:1883
      - MQTT_USER=client
      - MQTT_PASSWORD=TODO
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TODO
      - DISABLE_AUTH=true
    depends_on:
      - db
      - mqtt_broker
  tester:
    build:
      context: ./tester
    environment:
      - MQTT_BROKER=tcp://mqtt_broker:1883
      - MQTT_USER=client
      - MQTT_PASSWORD=TODO
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TODO
      - HUB_URL=http://hub:5151
    depends_on:
      - hub
  # webapp:
  #   build:
  #     context: ./webapp
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - URL_ENV=dev_compose
  #   depends_on:
  #     - hub
