CREATE DATABASE ioh;
\c ioh

CREATE TABLE IF NOT EXISTS clients (
  id VARCHAR(8) PRIMARY KEY,
  active BOOLEAN DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS configs (
  id SERIAL PRIMARY KEY,
  plant VARCHAR(24),
  water INT,
  clientid VARCHAR(8) UNIQUE NOT NULL REFERENCES clients(id),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON TABLE clients TO postgres;
GRANT ALL PRIVILEGES ON TABLE configs TO postgres;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres;

\dt
\d clients
\d configs
